### ISSUE TITLE
How jest coverage did count res.render() as tested?

### ISSUE THREAD

**Issue by gonzamvita** [gregjopa/express-app-testing-demo#13]
First, sorry to create an issue to ask a question. Its already some time trying to solve this but I don't find an explanation.

I see in your tests [this one](https://github.com/gregjopa/express-app-testing-demo/blob/master/app/__tests__/app.test.js#L11) where you test your root route.
Jest coverage is counting `res.render()` as tested at [this point](https://github.com/gregjopa/express-app-testing-demo/blob/master/app/route.js#L19) which seems perfectly fine to me.

In my case I have this test 

```js
describe('index route', () => {
  test('should return 200 OK', async () => {
    return request(app)
      .get('/')
      .expect('Content-Type', /html/)
      .expect(200)
      .then((response) => {
        expect(response.text).toMatch(
          /<title>Express<\/title>/
        )
      })
  })
})
```

For this route

```js
var express = require('express')
var router = express.Router()

/* GET home page. */
router.get('/', (req, res, next) => {
  return res.render('index', { title: 'Express' })
})

module.exports = router
```

And jest --coverage directly points at this line as _Uncovered line_:
```js
return res.render('index', { title: 'Express' })
```

Did you face this problem while creating your example?

Thank you very much,

**Comment by gregjopa** [comment]
Hi @gonzamvita, can you try removing the `async` keyword from your test? Ex:

```js
test('should return 200 OK', () => {
  return request(app)
  ...
``` 

It shouldn't be needed since <s>Mocha</s> Jest already knows it's an async test because the code is returning a Promise. Please try that and let me know how it goes.

**Comment by gregjopa** [comment]
@gonzamvita I'm going to close this out. Feel free to re-open if you still need help.
